### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by WUD2018** [Orin-beep/HOTSPOT#4]
Hey there,

Thanks for developing this software.

I bumped into some issues here: 

There is nothing wrong when I run the example data.

But, when I try mine (~ 450 MB after pretreatment by preprocessing.py), the pipeline reported error below. Could you please help me out? I guess somewhere in the HOTSPOT.py uses gpu? is it possible to not use it?

Identifying classes in Bacteria ...
76793 plasmid contigs to be predicted ...
Traceback (most recent call last):
  File "/home/disk1/HOTSPOT/HOTSPOT.py", line 181, in <module>
    logit, _ = model(sentence)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _c                                                                         all_impl
    return forward_call(*input, **kwargs)
  File "/home/disk1/HOTSPOT/library/model.py", line 210, in forward
    feat1 = self.Trans1(sentence1)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _c                                                                         all_impl
    return forward_call(*input, **kwargs)
  File "/home/disk1/HOTSPOT/library/model.py", line 170, in forward
    enc_src = self.encoder(src, src_mask)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _c                                                                         all_impl
    return forward_call(*input, **kwargs)
  File "/home/disk1/HOTSPOT/library/model.py", line 127, in forward
    out = self.layers(out, out, out, mask)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _c                                                                         all_impl
    return forward_call(*input, **kwargs)
  File "/home/disk1/HOTSPOT/library/model.py", line 84, in forward
    attention = self.attention(value, key, query, mask)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _c                                                                         all_impl
    return forward_call(*input, **kwargs)
  File "/home/disk1/HOTSPOT/library/model.py", line 39, in forward
    energy = torch.einsum("nqhd,nkhd->nhqk", [queries, keys])
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/functional.py", line 358, in einsum
    return einsum(equation, *_operands)
  File "/home/disk1/Anaconda3/envs/hotspot/lib/python3.8/site-packages/torch/functional.py", line 360, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]

RuntimeError: CUDA out of memory. Tried to allocate 978.00 MiB (GPU 0; 1.95 GiB total capacity; 898.40 MiB already a                                                                         llocated; 615.62 MiB free; 938.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try se                                                                         tting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Orin-beep** [comment]
Hello there,

Thank you for using HOTSPOT. A new version of the 'HOTSPOT.py' file has been uploaded, so please replace your current 'HOTSPOT.py' file.

Then, to run the program with CPU (which may result in slower prediction process), you have to include the '--device cpu' flag when running HOTSPOT.py.

Should you encounter any difficulties or have further inquiries, feel free to discuss with me later!

**Comment by Orin-beep** [comment]
Hi there! I apologize for the delay in my response.

A new version of HOTSPOT has been released, bringing significant improvements in terms of reduced model size and computational complexity. If you're still interested in HOTSPOT, I encourage you to try out the new version for plasmid host prediction.

If you have any new questions, such as inquiries about GPU requirements or any other topic, please don't hesitate to ask. I'm here to help you out!
